# Generated by Django 2.1.4 on 2018-12-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10, unique=True)),
                ('colony_type', models.CharField(max_length=25)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colony_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=4000)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colony_logs', to='colonymgr.Colony')),
            ],
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queen_no', models.CharField(max_length=10, unique=True)),
                ('queen_color', models.CharField(max_length=10)),
                ('cell_install_at', models.DateTimeField(null=True)),
                ('birth_at', models.DateTimeField(null=True)),
                ('laying_at', models.DateTimeField(null=True)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queens', to='colonymgr.Colony')),
            ],
        ),
        migrations.CreateModel(
            name='Queen_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=4000)),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queen_logs', to='colonymgr.Queen')),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='colony',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colonys', to='colonymgr.Yard'),
        ),
    ]
