# Generated by Django 2.1.4 on 2018-12-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonymgr', '0002_queen_yard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colony',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
