# Generated by Django 2.1.4 on 2018-12-08 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colonymgr', '0003_auto_20181208_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colonies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queen',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queens', to=settings.AUTH_USER_MODEL),
        ),
    ]
