# Generated by Django 2.1.4 on 2018-12-08 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonymgr', '0004_auto_20181208_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colonies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queen',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queens', to=settings.AUTH_USER_MODEL),
        ),
    ]
