# Generated by Django 2.1.4 on 2018-12-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonymgr', '0005_auto_20181208_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony_log',
            name='visited_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='queen_log',
            name='visited_at',
            field=models.DateTimeField(null=True),
        ),
    ]
